### Cadastro de usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Everton Andrade",
  "email": "everton@example.com",
  "password": "securepassword123"
}

### Listagem de produtos
GET http://localhost:3000/products

### Visualizar produto
GET http://localhost:3000/products/67871adfe6019bd9f598687c

### Adicionar um item ao carrinho
POST http://localhost:3000/cart/6788514f1e3af3fafaa3a51a
Content-Type: application/json

{
  "productId": "67871adfe6019bd9f598687c",
  "quantity": 1
}

### Visualizar carrinho de usuário
GET http://localhost:3000/cart/6788514f1e3af3fafaa3a51a
Content-Type: application/json


### Finalizar Compra
POST http://localhost:3000/purchase/6788514f1e3af3fafaa3a51a
Content-Type: application/json

{
  "userId": "63f5aef4e6e543001edb0a7e" 
}

### Consultar Estatísticas de Compras
GET http://localhost:3000/purchases/6788514f1e3af3fafaa3a51a/stats
