### Cadastro de usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Everton Andrade",
  "email": "everton@example.com",
  "password": "securepassword123"
}

### Listagem de produtos
GET http://localhost:3000/products

### Visualizar produto
GET http://localhost:3000/products/:productId

### Adicionar um item ao carrinho
POST http://localhost:3000/cart/:userId
Content-Type: application/json

{
  "productId": "",
  "quantity": 1
}

### Visualizar carrinho de usuário
GET http://localhost:3000/cart/:userId
Content-Type: application/json


### Finalizar Compra
POST http://localhost:3000/purchase/:userId
Content-Type: application/json

{
  "userId": "" 
}

### Consultar Estatísticas de Compras
GET http://localhost:3000/purchases/:userId/stats
